version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile_Node
    container_name: app_backend
    ports:
      - "3000:3000"
    networks:
      - backend

  redis:
    build:
      context: .
      dockerfile: Dockerfile_Redis
    container_name: my_redis
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    build:
      context: .
      dockerfile: Dockerfile_Mongo
    container_name: my_mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

networks:
  backend:

volumes:
  mongo_data:
